### ISSUE TITLE
?timeframe parameter doesn't seem to work anymore

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-beacon-dashboard#204]
https://beacon.ft.com/graph/opt-in?timeframe=this_90_days

**Comment by adambraimbridge** [comment]
Fixed. E.g: 
![image](https://cloud.githubusercontent.com/assets/224547/10227307/7bafec66-6864-11e5-86dd-983672324652.png)
https://beacon.ft.com/graph/opt-in?timeframe=this_60_days
