### ISSUE TITLE
Dashboard ideas

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/next-beacon-dashboard#83]
- [x] Top 404 URLs

**Comment by adambraimbridge** [comment]
- [ ] Top 404 URLs
- [ ] active search usage - step (1) is # of users, step (2) is # of people visiting /search, step (3) is # of people visiting an article with a /search referrer

**Comment by adambraimbridge** [comment]
- [ ] active search usage 
step (1) is # of users, 
step (2) is # of people visiting /search, 
step (3) is # of people visiting an article with a /search referrer

**Comment by adambraimbridge** [comment]
- [ ] Merge [globalNavigation](https://beacon.ft.com/graph/active-usage?feature=globalNavigation) into [navigation](https://beacon.ft.com/graph/navigation)

**Comment by adambraimbridge** [comment]
- [ ] Navigation dashboard: Add some kind of breakdown for primary, secondary and tertiary navigation

**Comment by adambraimbridge** [comment]
Active usage: Device breakdown
For each of the [active usage dashboards](https://beacon.ft.com/graph/active-usage?feature=globalNavigation):
- [ ] Show metrics for S, M and L (like [Device usage](https://beacon.ft.com/graph/uniques/by-device))

**Comment by adambraimbridge** [comment]
For https://beacon.ft.com/graph/uniques/by-device
- [ ] Add list of URLs with "page.location.type" of "unknown"

https://api.keen.io/3.0/projects/5486efb559949a0a311510fa/queries/count_unique?api_key=e6a84805d809660015224f8ddd0f9cac85549a518342a9186b3009674bfd2064ad47eb28d86fe72d94defb436995c572ce3dee1247333ae7ca0925fdb99847de04855af279fc6bd2ee6b1fe5b088022d5982b4867d83940c2aa1c7b8d4d6ba9208f450b62c1566fd1aacb36c25d4e2cd&event_collection=dwell&target_property=page.location.href&group_by=page.location.href&timezone=UTC&filters=%5B%7B%22property_name%22%3A%22page.location.type%22%2C%22operator%22%3A%22eq%22%2C%22property_value%22%3A%22unknown%22%7D%5D

**Comment by commuterjoy** [comment]
@adambraimbridge i deleted that link. remember this is a public forum and we don't want api keys leaking.

**Comment by adambraimbridge** [comment]
- [ ] Solution for saving queries (for performance benefits)
"Saved Queries also give us the opportunity to improve response times for queries you run again and again."
https://keen.io/docs/api/#create-a-saved-query
